name: Continuous Integration
on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: Homework 2 Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Build
        run: npm run build